algoritmo "Exercício 1"
// Função : Faça um programa que receba dois números, calcule e mostre a subtração do primeiro número pelo segundo.
// Autor :  Deise S. Alves
// Data : 24/07/2020
// Seção de Declarações 
var
A, B, C : inteiro
inicio
escreval (" ")
escreval ("Digite um numero: ")
leia (A)
escreval ("Digite outro numero: ")
leia (B)
C <- A - B
escreval (C," eh o resultado de ", A, " - ", B)
fimalgoritmo
